# Generated by Django 5.0.6 on 2024-06-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=200)),
                ("description", models.TextField(max_length=1000, null=True)),
                ("add_on", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PasteDataInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(max_length=3500, null=True)),
                ("add_on", models.DateTimeField(auto_now=True)),
                ("tags", models.CharField(max_length=250)),
                ("has_been_read", models.BooleanField(default=False)),
                ("password_protected", models.BooleanField(default=False)),
                (
                    "password_key",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("code", models.CharField(blank=True, max_length=18)),
                (
                    "expiration_choice",
                    models.CharField(
                        choices=[
                            ("never", "Never"),
                            ("burn_after_read", "Burn After Read"),
                            ("1day", "1 Day"),
                            ("1week", "1 Week"),
                            ("1month", "1 Month"),
                        ],
                        default="never",
                        max_length=15,
                    ),
                ),
            ],
        ),
    ]
